/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Actions: typeof import('./src/components/AlertDetail/Actions.vue')['default']
    AlertActions: typeof import('./src/components/AlertActions.vue')['default']
    AlertDetail: typeof import('./src/components/AlertDetail/index.vue')['default']
    AlertIndicator: typeof import('./src/components/AlertIndicator.vue')['default']
    AlertList: typeof import('./src/components/AlertList.vue')['default']
    AlertListFilter: typeof import('./src/components/AlertListFilter.vue')['default']
    Banner: typeof import('./src/components/lib/Banner.vue')['default']
    DateTime: typeof import('./src/components/lib/DateTime.vue')['default']
    Detail: typeof import('./src/components/AlertDetail/Detail.vue')['default']
    EscalationTriggersInformationDialog: typeof import('./src/components/auth/EscalationTriggersInformationDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    History: typeof import('./src/components/AlertDetail/History.vue')['default']
    ListButtonAdd: typeof import('./src/components/lib/ListButtonAdd.vue')['default']
    ProfileInfo: typeof import('./src/components/auth/ProfileInfo.vue')['default']
    ProfileMe: typeof import('./src/components/auth/ProfileMe.vue')['default']
    ReportFilter: typeof import('./src/components/reports/ReportFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./src/components/lib/Snackbar.vue')['default']
    TopFlapping: typeof import('./src/components/reports/TopFlapping.vue')['default']
    TopOffenders: typeof import('./src/components/reports/TopOffenders.vue')['default']
    TopStanding: typeof import('./src/components/reports/TopStanding.vue')['default']
    UserConfirm: typeof import('./src/components/auth/UserConfirm.vue')['default']
    UserForgot: typeof import('./src/components/auth/UserForgot.vue')['default']
    UserLogin: typeof import('./src/components/auth/UserLogin.vue')['default']
    UserLogout: typeof import('./src/components/auth/UserLogout.vue')['default']
    UserReset: typeof import('./src/components/auth/UserReset.vue')['default']
    UserSignup: typeof import('./src/components/auth/UserSignup.vue')['default']
  }
}
