/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Actions: typeof import('./src/components/AlertDetail/Actions.vue')['default']
    AlertActions: typeof import('./src/components/AlertActions.vue')['default']
    AlertDetail: typeof import('./src/components/AlertDetail/index.vue')['default']
    AlertIndicator: typeof import('./src/components/AlertIndicator.vue')['default']
    AlertList: typeof import('./src/components/lists/AlertList.vue')['default']
    AlertListFilter: typeof import('./src/components/AlertListFilter.vue')['default']
    Banner: typeof import('./src/components/lib/Banner.vue')['default']
    ChangeActiveState: typeof import('./src/components/dialogs/ChangeActiveState.vue')['default']
    ChangeActiveStateBulk: typeof import('./src/components/dialogs/ChangeActiveStateBulk.vue')['default']
    copy: typeof import('./src/components/dialogs/UserAdd copy.vue')['default']
    DateEdit: typeof import('./src/components/DateEdit.vue')['default']
    DateTime: typeof import('./src/components/lib/DateTime.vue')['default']
    Detail: typeof import('./src/components/AlertDetail/Detail.vue')['default']
    EscalationRuleAdd: typeof import('./src/components/dialogs/add/EscalationRuleAdd.vue')['default']
    EscalationRuleList: typeof import('./src/components/lists/EscalationRuleList.vue')['default']
    GCheckbox: typeof import('./src/components/GCheckbox.vue')['default']
    GCombobox: typeof import('./src/components/GCombobox.vue')['default']
    GroupEdit: typeof import('./src/components/GroupEdit.vue')['default']
    GSelect: typeof import('./src/components/GSelect.vue')['default']
    GSwitch: typeof import('./src/components/GSwitch.vue')['default']
    GTextField: typeof import('./src/components/GTextField.vue')['default']
    History: typeof import('./src/components/AlertDetail/History.vue')['default']
    InformationDialog: typeof import('./src/components/InformationDialog.vue')['default']
    LineEdit: typeof import('./src/components/LineEdit.vue')['default']
    ListButtonAdd: typeof import('./src/components/lib/ListButtonAdd.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
    NotificationRuleAdd: typeof import('./src/components/dialogs/add/NotificationRuleAdd.vue')['default']
    NotificationRuleDeactivate: typeof import('./src/components/NotificationRule/NotificationRuleDeactivate.vue')['default']
    NotificationRuleDeactivateBulk: typeof import('./src/components/NotificationRule/NotificationRuleDeactivateBulk.vue')['default']
    NotificationRuleList: typeof import('./src/components/lists/NotificationRuleList.vue')['default']
    OnCallAdd: typeof import('./src/components/dialogs/add/OnCallAdd.vue')['default']
    ProfileInfo: typeof import('./src/components/auth/ProfileInfo.vue')['default']
    ProfileMe: typeof import('./src/components/auth/ProfileMe.vue')['default']
    ReportFilter: typeof import('./src/components/reports/ReportFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./src/components/lib/Snackbar.vue')['default']
    TopFlapping: typeof import('./src/components/reports/TopFlapping.vue')['default']
    TopOffenders: typeof import('./src/components/reports/TopOffenders.vue')['default']
    TopStanding: typeof import('./src/components/reports/TopStanding.vue')['default']
    User: typeof import('./src/components/NotificationRule/User.vue')['default']
    UserAdd: typeof import('./src/components/dialogs/add/UserAdd.vue')['default']
    UserConfirm: typeof import('./src/components/auth/UserConfirm.vue')['default']
    UserForgot: typeof import('./src/components/auth/UserForgot.vue')['default']
    UserLogin: typeof import('./src/components/auth/UserLogin.vue')['default']
    UserLogout: typeof import('./src/components/auth/UserLogout.vue')['default']
    UserReset: typeof import('./src/components/auth/UserReset.vue')['default']
    UserSignup: typeof import('./src/components/auth/UserSignup.vue')['default']
  }
}
