/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/(Auth)/Confirm/[token]': RouteRecordInfo<'/(Auth)/Confirm/[token]', '/Confirm/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/(Auth)/Forgot': RouteRecordInfo<'/(Auth)/Forgot', '/Forgot', Record<never, never>, Record<never, never>>,
    '/(Auth)/Login': RouteRecordInfo<'/(Auth)/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/(Auth)/Reset/[token]': RouteRecordInfo<'/(Auth)/Reset/[token]', '/Reset/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/(Auth)/Signup': RouteRecordInfo<'/(Auth)/Signup', '/Signup', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/Alert/[id]': RouteRecordInfo<'/Alert/[id]', '/Alert/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Alerts': RouteRecordInfo<'/Alerts', '/Alerts', Record<never, never>, Record<never, never>>,
    '/Blackouts': RouteRecordInfo<'/Blackouts', '/Blackouts', Record<never, never>, Record<never, never>>,
    '/EscalationRules': RouteRecordInfo<'/EscalationRules', '/EscalationRules', Record<never, never>, Record<never, never>>,
    '/Heartbeats': RouteRecordInfo<'/Heartbeats', '/Heartbeats', Record<never, never>, Record<never, never>>,
    '/History': RouteRecordInfo<'/History', '/History', Record<never, never>, Record<never, never>>,
    '/Keys': RouteRecordInfo<'/Keys', '/Keys', Record<never, never>, Record<never, never>>,
    '/NotificationChannels': RouteRecordInfo<'/NotificationChannels', '/NotificationChannels', Record<never, never>, Record<never, never>>,
    '/NotificationDelays': RouteRecordInfo<'/NotificationDelays', '/NotificationDelays', Record<never, never>, Record<never, never>>,
    '/NotificationGroups': RouteRecordInfo<'/NotificationGroups', '/NotificationGroups', Record<never, never>, Record<never, never>>,
    '/NotificationHistory': RouteRecordInfo<'/NotificationHistory', '/NotificationHistory', Record<never, never>, Record<never, never>>,
    '/NotificationRules/': RouteRecordInfo<'/NotificationRules/', '/NotificationRules', Record<never, never>, Record<never, never>>,
    '/NotificationRules/[id]': RouteRecordInfo<'/NotificationRules/[id]', '/NotificationRules/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/NotificationSend': RouteRecordInfo<'/NotificationSend', '/NotificationSend', Record<never, never>, Record<never, never>>,
    '/OnCall': RouteRecordInfo<'/OnCall', '/OnCall', Record<never, never>, Record<never, never>>,
    '/Perms': RouteRecordInfo<'/Perms', '/Perms', Record<never, never>, Record<never, never>>,
    '/Profile': RouteRecordInfo<'/Profile', '/Profile', Record<never, never>, Record<never, never>>,
    '/Reports': RouteRecordInfo<'/Reports', '/Reports', Record<never, never>, Record<never, never>>,
    '/Settings': RouteRecordInfo<'/Settings', '/Settings', Record<never, never>, Record<never, never>>,
    '/Users': RouteRecordInfo<'/Users', '/Users', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/(Auth)/Confirm/[token].vue': {
      routes: '/(Auth)/Confirm/[token]'
      views: never
    }
    'src/pages/(Auth)/Forgot.vue': {
      routes: '/(Auth)/Forgot'
      views: never
    }
    'src/pages/(Auth)/Login.vue': {
      routes: '/(Auth)/Login'
      views: never
    }
    'src/pages/(Auth)/Reset/[token].vue': {
      routes: '/(Auth)/Reset/[token]'
      views: never
    }
    'src/pages/(Auth)/Signup.vue': {
      routes: '/(Auth)/Signup'
      views: never
    }
    'src/pages/[...all].vue': {
      routes: '/[...all]'
      views: never
    }
    'src/pages/Alert/[id].vue': {
      routes: '/Alert/[id]'
      views: never
    }
    'src/pages/Alerts.vue': {
      routes: '/Alerts'
      views: never
    }
    'src/pages/Blackouts.vue': {
      routes: '/Blackouts'
      views: never
    }
    'src/pages/EscalationRules.vue': {
      routes: '/EscalationRules'
      views: never
    }
    'src/pages/Heartbeats.vue': {
      routes: '/Heartbeats'
      views: never
    }
    'src/pages/History.vue': {
      routes: '/History'
      views: never
    }
    'src/pages/Keys.vue': {
      routes: '/Keys'
      views: never
    }
    'src/pages/NotificationChannels.vue': {
      routes: '/NotificationChannels'
      views: never
    }
    'src/pages/NotificationDelays.vue': {
      routes: '/NotificationDelays'
      views: never
    }
    'src/pages/NotificationGroups.vue': {
      routes: '/NotificationGroups'
      views: never
    }
    'src/pages/NotificationHistory.vue': {
      routes: '/NotificationHistory'
      views: never
    }
    'src/pages/NotificationRules/index.vue': {
      routes: '/NotificationRules/'
      views: never
    }
    'src/pages/NotificationRules/[id].vue': {
      routes: '/NotificationRules/[id]'
      views: never
    }
    'src/pages/NotificationSend.vue': {
      routes: '/NotificationSend'
      views: never
    }
    'src/pages/OnCall.vue': {
      routes: '/OnCall'
      views: never
    }
    'src/pages/Perms.vue': {
      routes: '/Perms'
      views: never
    }
    'src/pages/Profile.vue': {
      routes: '/Profile'
      views: never
    }
    'src/pages/Reports.vue': {
      routes: '/Reports'
      views: never
    }
    'src/pages/Settings.vue': {
      routes: '/Settings'
      views: never
    }
    'src/pages/Users.vue': {
      routes: '/Users'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
