/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Alert/[id]': RouteRecordInfo<'/Alert/[id]', '/Alert/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Alerts': RouteRecordInfo<'/Alerts', '/Alerts', Record<never, never>, Record<never, never>>,
    '/EscalationRules': RouteRecordInfo<'/EscalationRules', '/EscalationRules', Record<never, never>, Record<never, never>>,
    '/Heartbeats': RouteRecordInfo<'/Heartbeats', '/Heartbeats', Record<never, never>, Record<never, never>>,
    '/History': RouteRecordInfo<'/History', '/History', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/NotificationHistory': RouteRecordInfo<'/NotificationHistory', '/NotificationHistory', Record<never, never>, Record<never, never>>,
    '/NotificationRules/': RouteRecordInfo<'/NotificationRules/', '/NotificationRules', Record<never, never>, Record<never, never>>,
    '/NotificationRules/[id]': RouteRecordInfo<'/NotificationRules/[id]', '/NotificationRules/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/OnCall': RouteRecordInfo<'/OnCall', '/OnCall', Record<never, never>, Record<never, never>>,
    '/Signup': RouteRecordInfo<'/Signup', '/Signup', Record<never, never>, Record<never, never>>,
    '/Users': RouteRecordInfo<'/Users', '/Users', Record<never, never>, Record<never, never>>,
  }
}
